version: "3"
services:
  db:
    image: mysql:5.7
    container_name: db_container
    volumes:
      - db-volume:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      TZ: "Asia/Tokyo"
      MYSQL_DATABASE: monstar
      MYSQL_USER: test
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password

  # db:
  #   image: postgres:14
  #   volumes:
  #     - ./postgres/data:/var/lib/postgresql/data
  #     - ./postgres/initdb:/docker-entrypoint-initdb.d
  #   ports:
  #     - "5432:5432"
  #   environment:
  #     - TZ=Asia/Tokyo
  #     - POSTGRES_DB=monstar
  #     - POSTGRES_USER=postgres
  #     - POSTGRES_PASSWORD=password

volumes:
  db-volume:
    driver: local
