version: "3"
services:
  app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/app
    environment:
      - PORT=8080
      - DB_HOST=db
      - DB_PORT=3306
      - DB_NAME=monstar
      - DB_USER=test
      - DB_PASSWORD=password
      - SECRET=this_is_not_secret
    depends_on:
      - db

  db:
    image: mysql:5.7
    container_name: db_container
    volumes:
      - db-volume:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      TZ: "Asia/Tokyo"
      MYSQL_DATABASE: monstar
      MYSQL_USER: test
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password

volumes:
  db-volume:
    driver: local
